name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
        if: always()
      - name: lint typescript
        run: npm run lint:ts
        if: always()
      - name: lint scss
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
        if: always()
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: storybook testing
        run: npm run test:ui:ci
